# netlify.toml

[build]
  command = "hugo mod get -u && hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  NODE_ENV = "production"
  GO_VERSION = "1.16"
  TZ = "America/Edmonton"  # Set to preferred timezone

[context.production.environment]
  HUGO_VERSION = "0.127.0"
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.127.0"

# Added by GSW - Sun, Aug 11, 2024 to test gpx maps with gpx.studio
# as per this guy's solution: https://discourse.gohugo.io/t/access-control-allow-origin-cors-question/40613
# Later I asked the "AI Help" at Netlify and it gave this same answer - put this code in the site netlify.toml
[headers]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"